services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hh-helper

    ports:
    - "8008:${PORT}"

    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port ${PORT} --reload"

    env_file:
      - ./.env
    volumes:
      - ./:/app